# Generated by Django 5.2.9 on 2025-12-29 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('donation', 'Donation'), ('event', 'Event'), ('task', 'Task'), ('campaign', 'Campaign')], default='info', max_length=50)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('DONATION', 'Donation'), ('VERIFICATION', 'Verification'), ('SHELTER', 'Shelter'), ('VOLUNTEER', 'Volunteer'), ('CASE', 'Case Management')], default='SYSTEM', max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
