# Generated by Django 5.2.11 on 2026-02-24 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bug_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bug report',
                'verbose_name_plural': 'bug reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_bu_status_cd1dd6_idx'), models.Index(fields=['bug_type'], name='accounts_bu_bug_typ_63b917_idx'), models.Index(fields=['created_at'], name='accounts_bu_created_1c20b4_idx')],
            },
        ),
    ]
