# Generated by Django 5.1.5 on 2026-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='numeric_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
