# Generated by Django 5.2.9 on 2025-12-30 04:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_homes', '0003_incidentreport_resourcerequest'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('application_note', models.TextField(blank=True, help_text='Why do you want to do this task?')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'task application',
                'verbose_name_plural': 'task applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='volunteers__assigne_8c179c_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='volunteers.volunteer'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(default='General Location', help_text='Specific location/address', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='result_summary',
            field=models.TextField(blank=True, help_text='Summary of the task outcome'),
        ),
        migrations.AddField(
            model_name='task',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='shelter_homes.shelterhome'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('SHELTER', 'Shelter Assistance'), ('COMMUNITY', 'Community Service'), ('EVENT', 'Event Support'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['shelter'], name='volunteers__shelter_a19221_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['approval_status'], name='volunteers__approva_9203b5_idx'),
        ),
        migrations.AddField(
            model_name='taskapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskapplication',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.task'),
        ),
        migrations.AddField(
            model_name='taskapplication',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_applications', to='volunteers.volunteer'),
        ),
        migrations.AlterUniqueTogether(
            name='taskapplication',
            unique_together={('task', 'volunteer')},
        ),
    ]
