# Generated by Django 5.2.9 on 2025-12-30 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_taskapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_to_donors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='post_to_shelters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='post_to_volunteers',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='volunteers.event')),
            ],
            options={
                'verbose_name': 'event photo',
                'verbose_name_plural': 'event photos',
            },
        ),
    ]
