# Generated by Django 5.2.11 on 2026-02-24 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteergroup_groupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'availability slot',
                'verbose_name_plural': 'availability slots',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='trainingcompletion',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.TextField(blank=True, help_text='Available days/times (Legacy)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills (Legacy)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability_slots',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.availabilityslot'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills_list',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.skill'),
        ),
    ]
