# Generated by Django 5.0.14 on 2025-12-20 12:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/photos/')),
                ('photo_consent', models.BooleanField(default=False, help_text='Parental consent for photo')),
                ('legal_status', models.CharField(choices=[('WITH_PARENTS', 'Living with Parents'), ('ORPHAN_SINGLE', 'Single Orphan'), ('ORPHAN_DOUBLE', 'Double Orphan'), ('ABANDONED', 'Abandoned'), ('COURT_ORDER', 'Under Court Order'), ('GUARDIANSHIP', 'Under Guardianship')], max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100)),
                ('court_order_number', models.CharField(blank=True, max_length=100)),
                ('in_school', models.BooleanField(default=True)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('education_support_needed', models.BooleanField(default=False)),
                ('health_status', models.TextField(blank=True, help_text='General health notes')),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_description', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('requires_counseling', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
                'ordering': ['family', 'date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed'), ('TRANSFERRED', 'Transferred')], default='OPEN', max_length=20)),
                ('intervention_plan', models.TextField(help_text='Detailed intervention plan')),
                ('expected_outcomes', models.TextField(blank=True)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('target_closure_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('closure_reason', models.TextField(blank=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'CASE_WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_milestone', models.BooleanField(default=False, help_text='Mark as significant milestone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='case_management.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'case note',
                'verbose_name_plural': 'case notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_code', models.CharField(help_text='Unique family identifier', max_length=20, unique=True)),
                ('primary_contact_name', models.CharField(max_length=200)),
                ('primary_contact_phone', models.CharField(max_length=20)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_relationship', models.CharField(help_text='e.g., Mother, Father, Guardian', max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(help_text='Detailed physical address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('vulnerability_score', models.IntegerField(help_text='Calculated vulnerability score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vulnerability_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('total_members', models.IntegerField(default=0)),
                ('children_count', models.IntegerField(default=0)),
                ('adults_count', models.IntegerField(default=0)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income_source', models.CharField(blank=True, max_length=200)),
                ('housing_type', models.CharField(blank=True, help_text='e.g., Rented, Owned, Informal settlement', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_case_worker', models.ForeignKey(limit_choices_to={'role': 'CASE_WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_families', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_CARD', 'ID Card'), ('BIRTH_CERT', 'Birth Certificate'), ('PHOTO', 'Photo'), ('MEDICAL', 'Medical Record'), ('SCHOOL', 'School Document'), ('COURT', 'Court Order'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/')),
                ('consent_obtained', models.BooleanField(default=False)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('consent_given_by', models.CharField(blank=True, max_length=200)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='case_management.child')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='case_management.family')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='case_management.family'),
        ),
        migrations.AddField(
            model_name='case',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='case_management.family'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('INITIAL', 'Initial Assessment'), ('FOLLOW_UP', 'Follow-up Assessment'), ('ANNUAL', 'Annual Review'), ('EMERGENCY', 'Emergency Assessment')], max_length=20)),
                ('assessment_date', models.DateField()),
                ('economic_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('housing_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('health_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('education_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('safety_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('urgent_needs', models.TextField(blank=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_conducted', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='case_management.family')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['family_code'], name='case_manage_family__4f1c65_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['vulnerability_level'], name='case_manage_vulnera_943d41_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['assigned_case_worker'], name='case_manage_assigne_3be449_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['county'], name='case_manage_county_5d9c75_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['family'], name='case_manage_family__1cd9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['child'], name='case_manage_child_i_d8566e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='case_manage_documen_23dfb4_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['family', 'is_active'], name='case_manage_family__9f8c50_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['legal_status'], name='case_manage_legal_s_1c1532_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='case_manage_case_nu_e1437f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='case_manage_status_ee0964_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='case_manage_priorit_d6ee7e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_to'], name='case_manage_assigne_5fa77b_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['family', 'assessment_date'], name='case_manage_family__f1c694_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type'], name='case_manage_assessm_f8f8d9_idx'),
        ),
    ]
