# Generated by Django 5.1.5 on 2026-05-18 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='overall_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
