# Generated by Django 5.0.14 on 2025-12-20 12:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('facebook_post_id', models.CharField(blank=True, max_length=200)),
                ('twitter_post_id', models.CharField(blank=True, max_length=200)),
                ('instagram_post_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('newsletter_subscribed', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_recurring_donor', models.BooleanField(default=False)),
                ('total_donated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'donor',
                'verbose_name_plural': 'donors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor')),
                ('receipt_sent', models.BooleanField(default=False)),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.campaign')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donor')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CLOTHES', 'Clothes'), ('FOOD', 'Food/Perishables'), ('STATIONERY', 'School Supplies/Stationery'), ('ELECTRONICS', 'Electronics/Computers'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.CharField(help_text='e.g., "5 bags", "2 boxes"', max_length=100)),
                ('pickup_address', models.TextField()),
                ('preferred_pickup_date', models.DateField()),
                ('preferred_pickup_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING_PICKUP', 'Pending Pickup'), ('COLLECTED', 'Collected'), ('DISTRIBUTED', 'Distributed'), ('CANCELLED', 'Cancelled')], default='PENDING_PICKUP', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_donations', to='donations.donor')),
            ],
            options={
                'verbose_name': 'material donation',
                'verbose_name_plural': 'material donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('tax_deductible', models.BooleanField(default=True)),
                ('tax_year', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donations.donation')),
            ],
            options={
                'verbose_name': 'receipt',
                'verbose_name_plural': 'receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram')], max_length=20)),
                ('post_id', models.CharField(max_length=200)),
                ('post_url', models.URLField()),
                ('content', models.TextField()),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='donations.campaign')),
            ],
            options={
                'verbose_name': 'social media post',
                'verbose_name_plural': 'social media posts',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['slug'], name='donations_c_slug_59cb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='donations_c_status_8e86da_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='donations_c_start_d_6b8400_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['email'], name='donations_d_email_16156b_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['donor_type'], name='donations_d_donor_t_85d83c_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='donations_d_donor_i_b67ace_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign'], name='donations_d_campaig_62f8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['transaction_id'], name='donations_d_transac_1e2c54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediapost',
            unique_together={('platform', 'post_id')},
        ),
    ]
