# Generated by Django 5.0.1 on 2025-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('SHELTER', 'Shelter/Housing'), ('FOOD_SECURITY', 'Food Security'), ('DISASTER_RELIEF', 'Disaster Relief'), ('ENVIRONMENT', 'Environment'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
    ]
