# Generated by Django 5.2.11 on 2026-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_campaign_category_campaign_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdonation',
            name='status',
            field=models.CharField(choices=[('PENDING_PICKUP', 'Pending Pickup'), ('COLLECTED', 'Collected'), ('DISTRIBUTED', 'Distributed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_PICKUP', max_length=20),
        ),
    ]
