# Generated by Django 5.2.11 on 2026-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_materialdonation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='donor',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
