# Generated by Django 5.2.11 on 2026-02-24 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_mediaasset_source_type'),
        ('donations', '0004_alter_donor_email_alter_donor_full_name'),
        ('shelter_homes', '0004_shelterhome_latitude_shelterhome_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact_date', models.DateField(default=django.utils.timezone.now)),
                ('monetary_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated value of material impact if applicable', max_digits=12)),
                ('is_reported', models.BooleanField(default=False, help_text='Whether this impact has been submitted to admin')),
                ('admin_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacts', to='donations.donation')),
                ('material_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacts', to='donations.materialdonation')),
                ('media', models.ManyToManyField(blank=True, related_name='linked_impacts', to='blog.mediaasset')),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_records', to='shelter_homes.shelterhome')),
            ],
            options={
                'verbose_name': 'donation impact',
                'verbose_name_plural': 'donation impacts',
                'ordering': ['-impact_date'],
            },
        ),
    ]
