# Generated by Django 5.1.5 on 2026-04-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_donationimpact"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="callback_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="last_mpesa_result_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
