# Generated by Django 5.1.5 on 2026-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0006_donation_callback_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="mpesa_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
