# Generated by Django 5.1.5 on 2026-05-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_donation_mpesa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa')], max_length=20),
        ),
    ]
