# Generated by Django 5.1.5 on 2026-05-18 05:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_alter_donation_payment_method'),
        ('shelter_homes', '0006_alter_shelterhome_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('purpose_description', models.TextField(help_text='What these funds are intended for')),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank or M-Pesa transaction ref', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('AWAITING_RECEIPT', 'Awaiting Receipt'), ('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_created', to=settings.AUTH_USER_MODEL)),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='shelter_homes.shelterhome')),
            ],
            options={
                'verbose_name': 'disbursement',
                'verbose_name_plural': 'disbursements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='disbursement_receipts/%Y/%m/')),
                ('description', models.TextField(help_text='Details of how the funds were used')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('disbursement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donations.disbursement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'disbursement receipt',
                'verbose_name_plural': 'disbursement receipts',
            },
        ),
        migrations.CreateModel(
            name='DisbursementPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='disbursement_impact/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='donations.disbursementreceipt')),
            ],
            options={
                'verbose_name': 'disbursement photo',
                'verbose_name_plural': 'disbursement photos',
            },
        ),
    ]
