# Generated by Django 5.1.5 on 2026-05-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_wallet_disbursement_disbursementreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, help_text='Specific account/number funds were sent to'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
