# Generated by Django 6.0 on 2026-01-24 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_teammember_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Unique key for fetching content (e.g. "about-story")', max_length=100, unique=True)),
                ('section', models.CharField(choices=[('HERO', 'Hero Section'), ('ABOUT', 'About Section'), ('MISSION_VISION', 'Mission & Vision'), ('STATS', 'Statistics'), ('FOOTER', 'Footer Information'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, help_text='Main text content (supports Markdown)')),
                ('value', models.CharField(blank=True, help_text='Short value if needed (e.g. "50+")', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site content',
                'verbose_name_plural': 'site contents',
                'ordering': ['section', 'key'],
            },
        ),
    ]
