# Generated by Django 6.0 on 2026-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
