# Generated by Django 5.2.11 on 2026-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_mediaasset_shelter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if this is a cross-post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description (defaults to excerpt)', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (defaults to title)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_card',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with Large Image')], default='summary_large_image', max_length=20),
        ),
    ]
