# Generated by Django 5.2.11 on 2026-02-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_canonical_url_blogpost_og_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='source_type',
            field=models.CharField(choices=[('CAMPAIGN', 'Campaign'), ('STORY', 'Story/Blog'), ('SHELTER', 'Shelter'), ('TEAM', 'Team Member'), ('USER', 'User Profile'), ('IMPACT', 'Donation Impact'), ('GENERAL', 'General/Other')], default='GENERAL', max_length=20),
        ),
    ]
