# Generated by Django 5.1.5 on 2026-05-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_mediaasset_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageMedia',
            fields=[
            ],
            options={
                'verbose_name': 'landing page media',
                'verbose_name_plural': 'landing page media',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.mediaasset',),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='source_type',
            field=models.CharField(choices=[('CAMPAIGN', 'Campaign'), ('STORY', 'Story/Blog'), ('SHELTER', 'Shelter (Displayed on Landing Page Hero/Partner sections)'), ('TEAM', 'Team Member'), ('USER', 'User Profile'), ('IMPACT', 'Donation Impact'), ('GENERAL', 'General/Other')], default='GENERAL', max_length=20),
        ),
    ]
