# Generated by Django 5.0.14 on 2025-12-20 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dashboard_type', models.CharField(choices=[('EXECUTIVE', 'Executive Dashboard'), ('CASE_WORKER', 'Case Worker Dashboard'), ('VOLUNTEER_MANAGER', 'Volunteer Manager Dashboard'), ('DONOR_RELATIONS', 'Donor Relations Dashboard'), ('CUSTOM', 'Custom Dashboard')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(default=dict, help_text='Dashboard widget configuration')),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_with_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CHILDREN', 'Children Served'), ('FAMILIES', 'Families Supported'), ('DONATIONS', 'Donations'), ('VOLUNTEERS', 'Volunteers'), ('CASES', 'Cases'), ('SHELTERS', 'Shelter Homes')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit', models.CharField(help_text='e.g., children, KES, hours', max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('trend_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='reporting_k_categor_0f98b4_idx'), models.Index(fields=['period_start', 'period_end'], name='reporting_k_period__7080df_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DONATION_RECEIVED', 'Donation Received'), ('CASE_OPENED', 'Case Opened'), ('CASE_CLOSED', 'Case Closed'), ('VOLUNTEER_JOINED', 'Volunteer Joined'), ('VOLUNTEER_HOURS', 'Volunteer Hours Logged'), ('BLOG_VIEW', 'Blog Post Viewed'), ('CAMPAIGN_CREATED', 'Campaign Created'), ('SHELTER_PLACEMENT', 'Shelter Placement')], max_length=30)),
                ('event_data', models.JSONField(default=dict, help_text='Additional event data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'analytics event',
                'verbose_name_plural': 'analytics events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='reporting_a_event_t_74fe16_idx'), models.Index(fields=['user', 'timestamp'], name='reporting_a_user_id_1ef018_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('reporting_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('content', models.TextField(help_text='Report content')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='compliance/%Y/%m/')),
                ('metrics', models.JSONField(default=dict, help_text='Compliance metrics')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports_prepared', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compliance report',
                'verbose_name_plural': 'compliance reports',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['status'], name='reporting_c_status_3a67ed_idx'), models.Index(fields=['period_start', 'period_end'], name='reporting_c_period__7f56cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('DONATION', 'Donation Report'), ('VOLUNTEER', 'Volunteer Hours Report'), ('CASE', 'Case Management Report'), ('SHELTER', 'Shelter Home Report'), ('COMPLIANCE', 'Compliance Report'), ('FINANCIAL', 'Financial Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report filter parameters')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type'], name='reporting_r_report__5d34ee_idx'), models.Index(fields=['generated_at'], name='reporting_r_generat_9f5407_idx')],
            },
        ),
    ]
