# Generated by Django 5.0.1 on 2026-01-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='description',
            field=models.TextField(blank=True, help_text='Human readable description of the event'),
        ),
    ]
