# Generated by Django 5.2.11 on 2026-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_analyticsevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='reports/%Y/%m/'),
        ),
    ]
