# Generated by Django 5.0.14 on 2025-12-20 12:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterHome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField()),
                ('total_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_occupancy', models.IntegerField(default=0)),
                ('has_medical_facility', models.BooleanField(default=False)),
                ('has_education_facility', models.BooleanField(default=False)),
                ('has_counseling_services', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'SHELTER_PARTNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_shelter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shelter home',
                'verbose_name_plural': 'shelter homes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('MEDICAL', 'Medical Supplies'), ('EDUCATIONAL', 'Educational Materials'), ('BEDDING', 'Bedding'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(help_text='e.g., kg, pieces, boxes', max_length=50)),
                ('minimum_quantity', models.IntegerField(default=0, help_text='Alert when below this level')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='shelter_homes.shelterhome')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ['shelter_home', 'resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement_date', models.DateField()),
                ('expected_duration_days', models.IntegerField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TRANSFERRED', 'Transferred'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('placement_reason', models.TextField()),
                ('special_requirements', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_placements', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='case_management.child')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_created', to=settings.AUTH_USER_MODEL)),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='shelter_homes.shelterhome')),
            ],
            options={
                'verbose_name': 'placement',
                'verbose_name_plural': 'placements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('certificate_of_good_conduct', models.BooleanField(default=False)),
                ('certificate_expiry', models.DateField(blank=True, null=True)),
                ('training_certificates', models.TextField(blank=True, help_text='List of training certificates')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credentials', to='shelter_homes.shelterhome')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff credential',
                'verbose_name_plural': 'staff credentials',
                'ordering': ['shelter_home', 'staff_name'],
            },
        ),
        migrations.AddIndex(
            model_name='shelterhome',
            index=models.Index(fields=['county'], name='shelter_hom_county_e891ad_idx'),
        ),
        migrations.AddIndex(
            model_name='shelterhome',
            index=models.Index(fields=['is_active'], name='shelter_hom_is_acti_8800d3_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['shelter_home', 'resource_type'], name='shelter_hom_shelter_3801ae_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['child'], name='shelter_hom_child_i_0bf10d_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['shelter_home'], name='shelter_hom_shelter_bb0eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['status'], name='shelter_hom_status_ce5aeb_idx'),
        ),
    ]
