# Generated by Django 5.2.9 on 2025-12-29 15:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_homes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterhome',
            name='age_range_max',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='age_range_min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs More Information')], default='PENDING', help_text='Admin approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shelters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='disability_accommodations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='disability_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='disability_types_supported',
            field=models.JSONField(blank=True, default=list, help_text='List of disability types supported'),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='fire_safety_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='gender_policy',
            field=models.CharField(choices=[('MALE_ONLY', 'Male Only'), ('FEMALE_ONLY', 'Female Only'), ('CO_ED', 'Co-Educational')], default='CO_ED', max_length=20),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='security_measures',
            field=models.TextField(blank=True, help_text='Describe security arrangements'),
        ),
        migrations.AlterField(
            model_name='shelterhome',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShelterPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shelter_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('photo_type', models.CharField(choices=[('EXTERIOR', 'Exterior View'), ('DORMITORY', 'Dormitory/Sleeping Area'), ('FACILITIES', 'Common Facilities'), ('PLAYGROUND', 'Play/Recreation Area'), ('DINING', 'Dining Area'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary display photo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shelter_homes.shelterhome')),
            ],
            options={
                'verbose_name': 'shelter photo',
                'verbose_name_plural': 'shelter photos',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
