# Generated by Django 5.0.1 on 2025-12-29 20:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_homes', '0002_shelterhome_age_range_max_shelterhome_age_range_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('actions_taken', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='shelter_homes.shelterhome')),
            ],
            options={
                'verbose_name': 'incident report',
                'verbose_name_plural': 'incident reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_category', models.CharField(choices=[('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('MEDICAL', 'Medical Supplies'), ('EDUCATIONAL', 'Educational Materials'), ('BEDDING', 'Bedding'), ('OTHER', 'Other')], max_length=20)),
                ('items_description', models.TextField(help_text='List of items needed and specific details')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_requests_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_requests_made', to=settings.AUTH_USER_MODEL)),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to='shelter_homes.shelterhome')),
            ],
            options={
                'verbose_name': 'resource request',
                'verbose_name_plural': 'resource requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
