# Generated by Django 5.2.11 on 2026-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_homes', '0003_incidentreport_resourcerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterhome',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
