# Generated by Django 5.1.5 on 2026-05-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_homes', '0005_make_location_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterhome',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Exact latitude coordinate (required for map pinning)', max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelterhome',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Exact longitude coordinate (required for map pinning)', max_digits=9),
            preserve_default=False,
        ),
    ]
