# Generated by Django 5.1.5 on 2026-05-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_homes', '0006_alter_shelterhome_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterhome',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='mpesa_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
